apiVersion: v1
kind: Namespace
metadata:
  name: cisco-react-1324-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cisco-react-deployment
  namespace: cisco-react-1324-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: eslattacr.azurecr.io/react-demo:ce4ca05b7c94789e785b02287cb2aaa4ce4

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cisco-react-label
  name: cisco-react-service
  namespace: cisco-react-1324-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---
