apiVersion: v1
kind: Namespace
metadata:
  name: react-example
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-example-demo
  namespace: react-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 440953937617.dkr.ecr.us-east-2.amazonaws.com/react-repo:0295eb1ba9aa05ea303a7f849c297e7065fc0ebd

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: react-example-demo
  name: react-example-demo
  namespace: react-example
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---
